"""Keyword categoriser (first match wins). Edit RULES to tune categories."""
import re
RULES=[
 ("Medical & Healthcare","Goods",r"\d\s?mg\b|\binj\b|\btab\b|\bsyp\b|oral rehydration|rehydration|clavicle|va anterior|locking plate|bone plate"),
 ("Vehicle Repair & Servicing","Service",r"modification of loading platform|lorry"),
 ("Manpower, Housekeeping & Support Services","Service",r"\bcourse\b|specialist course|training programme|workshop on"),
 ("Aircraft, Avionics & Aviation Ground Equipment","Goods",r"fod trap|wheel chock|bomb support|blanking streamer|dau-72|breather|bird shooter|pota cabin|a/c blanking"),
 ("Medical & Healthcare","Goods",r"lignocaine|diclofenac|atropine|tramadol|\bhcl\b|assay|\blyse\b|tibial|caliper|rhinoplasty|growth factor|pulsavac|lypocheck|meril|sulphate|therapy kit|bio rad|test kit, medical"),
 ("Chemicals, Lubricants & Consumables","Goods",r"bromadialone|fipronil|fenthion|baytex|foot powder|universal cleaner|corr prev|\bacf\b|inhibitor|bait|spray|microbial fuel"),
 ("Communication, Radar & Surveillance","Goods",r"mass alert|dvr|voice recorder|music system|infra red torch|torch"),
 ("Clothing, Textile, Bags & Tentage","Goods",r"dungaree|spats|tie set|customi[sz]ed gift|customi[sz]ed (coin|tie|sipper)|sling"),
 ("Furniture, Storage & Furnishings","Goods",r"anti ?fatigue mat|antistatic floor mat|floor mat|\bmat\b"),
 ("Sports, Gym & Training","Goods",r"speed cassette|chainring|cassette|bicycle|cycling"),
 ("Kitchen, Mess & Household","Goods",r"degchi|chapati|chaj for cleaning|ponii|poni large"),
 ("Electrical, Power & Lighting","Goods",r"stabli[sz]er|power contractor|conduit"),
 ("Tools, Machinery & Test Equipment","Goods",r"particle counter|regulator|manifold|cylinder|armoured suction hose|coupling|container|e-cart|dip tray|visuali[sz]er|protector|retainer casing|hose"),
 ("IT, Networking & Electronics","Goods",r"cartriedge|cartridge"),
 ("Equipment Repair, AMC & Calibration","Service",r"repair, maintenance|renewal/ ?re-?certification|re-certification|certification of|silver polishing|polishing of"),
 ("Medical & Healthcare","Goods",r"\btab\b|\binj\b|\bsyp\b|\bmg\b|\bcream\b|otoscope|diathermy|eye wear|syrup|ointment|\bdrops\b|\bampoule|\bvial\b|physio|medicine|pharmac"),
 ("Vehicle Repair & Servicing","Service",r"repair and overhauling service - (built up trucks|cars|buses|two wheeler|light motor|motor|tractor|trailer|jeep|ambulance|bus|truck|wheeled|crane|forklift|loader|skid)|repair of (lorry|jeep|truck|bus|car|vehicle)|vehicle repair|servicing of vehicle"),
 ("Equipment Repair, AMC & Calibration","Service",r"repair and overhauling service|^repair of|repair of |overhaul|\bamc\b|\bcamc\b|\bcmc\b|maintenance contract|annual maintenance|comprehensive maintenance|calibration service|hydrostatic test|full service and maintenance|servicing|refurbish|overhauling"),
 ("Manpower, Housekeeping & Support Services","Service",r"manpower|cleaning, sanitation|sanitation|housekeeping|laundry|security service|catering|hiring of|hiring service|custom bid for services|professional painting service|pest control|horticulture|gardening|transport service|taxi|cab hire|vehicle hiring|outsourc|facility management|disinfection|printing of|photography|event"),
 ("Security, Perimeter & Safety","Goods",r"fence|fencing|barrier|bollard|barricade|access control|spike|safety pin|protective|safety|fire extinguisher|fire alarm|metal detector|detector|de-bugging|debugging|scanner, baggage|razor|concertina"),
 ("Medical & Healthcare","Goods",r"medical|surgical|endoscop|forceps|stent|injection|dental|ophthalm|auroscope|x - ray|x-ray|ecg|ventilator|syringe|catheter|suture|tablet|capsule|infusion|glove|mask|bone|ortho|hemostatic|hospital|patient|bandage|dialysis|ultrasound|anaesth|laparoscop|speculum|sterili|autoclave|pharma|vaccine|surfactant|pulse oximeter|stretcher|wheelchair|oxygen|nebuli|blood|implant|diagnostic|reagent|haemo|hemo|urolog|dcr|cardiac|defibrill|monitor, patient|lab consumable|microscope|centrifuge"),
 ("Food, Provisions & Spices","Goods",r"cardamom|pepper|asafoetida|cinnamon|cumin|turmeric|coriander|masala|spice|\brice\b|wheat|atta|\bdal\b|pulse|sugar|\btea\b|coffee|edible oil|mustard oil|ghee|milk|biscuit|salt|jaggery|chilli|vegetable|fruit|egg|chicken|mutton|fish|ration|provision|flour|noodle|honey|cloves|garlic|onion|potato|tomato|dry fruit|almond|cashew|raisin|oil, "),
 ("Aircraft, Avionics & Aviation Ground Equipment","Goods",r"aircraft|\bapu\b|airdata|avionic|refuell|aviation|helicopter|\bmi-\d|kiran|hpt-32|mig|sukhoi|jaguar|mirage|radome|undercarriage|tow bar|towbar|ground support|\bgse\b|flight|squadron|runway|arrester|ils\b|airfield|air band|pitot|fuel bowser|bowser|hydraulic refilling|aero|gearbox|rotor|turbine|landing gear"),
 ("Communication, Radar & Surveillance","Goods",r"transceiver|\bvhf\b|\buhf\b|radio|walkie|night vision|search ?light|surveillance|radar|\bcctv\b|binocular|thermal|drone|antenna|satcom|jammer|handheld|hand-held|communication|\bmha qr|telescope|laser|periscope|sonar|\bgps\b|intercom|pa system|public address"),
 ("IT, Networking & Electronics","Goods",r"smartphone|smart phone|mobile|data wall|video conferenc|cyber|computer|laptop|desktop|printer|scanner|firewall|network|fibre|fiber|\bofc\b|optical|router|switch|server|\bups\b|photocopier|projector|monitor|tablet pc|\bcard\b|software|licen[cs]e|storage|\bssd\b|hard disk|keyboard|mouse|toner|cartridge|laminat|camera|camcorder|display|\blcd\b|\bled\b|display|rack mount|workstation|\bpc\b|antivirus|cable|wifi|wi-fi|modem|converter|battery|inverter|charger|electronic|\bpcb\b|sensor|circuit|controller|\bplc\b|oscilloscope|multimeter|\bic\b|capacitor|resistor|transformer|relay|connector"),
 ("Electrical, Power & Lighting","Goods",r"batter|lead acid|extension board|lamp|light|\bsolar|load bank|bleeder|resistor|load cell|thermocouple|inverter|\bups\b|transformer|switchgear|\bmcb\b|panel|wire|socket|flood|luminaire|bulb|tube light|helipad"),
 ("Vehicle Spares & Automotive Parts","Goods",r"seat cover|foot mat|filter|ignition|mirror|tyre|tire|brake|clutch|gasket|piston|bearing|\bdrag link|fuel pump|radiator|alternator|starter|spark|headlight|wiper|shock absorber|axle|steering|lub oil|engine oil|grease|coolant|belt|hose pipe|bumper|windshield|\bassy\b|vehicle|truck|trolley jack|jack|spare|tube gmi|carburet|suspension|gear box|transmission|exhaust|silencer|nut bolt|bolt|washer|seal|o-ring"),
 ("Tools, Machinery & Test Equipment","Goods",r"tester|analy[sz]er|trolley|lift|compressor|generator|\bdg set|pump|loader|welding|drill|grinder|lathe|machine|crane|hoist|jack|press|tool|torque|gauge|meter|calibrat|spanner|wrench|cutter|saw|motor|forklift|pallet|conveyor|boiler|air conditioner|\bac\b|split ac|refrigerat|cooler|chiller|water cooler|fan|heater|vacuum|pressure washer|sprayer|hydraulic|pneumatic|stand|fixture|jig|oscilloscope|signal generator|power supply"),
 ("Construction, Civil & Electrical Works","Works",r"site cleaning|lawn|landscap|wooden|batten|ballies|classroom|toilet|foundation|basement|partition wall|roofing|false ceiling|electrif|digging|laying|construction|civil|plaster|paint|building|road|drain|pavement|boundary wall|fencing|pipeline|plumbing|sanitary|tiles|flooring|renovation|masonry|concrete|cement|steel structure|shed|hangar|barrack|shelter|modular|prefab|\bpsp sheet|roof|ceiling|door|window|grill|gate|wiring|substation|\bhdpe|earthing|lightning"),
 ("Furniture, Storage & Furnishings","Goods",r"\\brack|locker|cabinet|almirah|carpet|curtain|\\btable\\b|chair|\\bdesk|sofa|\\bbed\\b|mattress|furniture|shelf|shelves|cupboard|bench|\\bblinds?\\b|\\brug\\b|pillow|blanket|\\bcot\\b|wardrobe|safe deposit|signage|gazebo|name board|sign board|signboard|glow sign|notice board|whiteboard|partition"),
 ("Clothing, Textile, Bags & Tentage","Goods",r"cover for|covers?\b|coat combat|combat|field dress|paulin|tarpaulin|uniform|shoe|boot|jacket|cloth|fabric|tent|shirt|trouser|cap\b|bag|rucksack|towel|jersey|glove|sock|belt|rope|net\b|canvas|sleeping|bedding|helmet|vest|apron|tracksuit|turban|lanyard|badge|banner|flag"),
 ("Kitchen, Mess & Household","Goods",r"tea set|dining|plate|bowl|cutlery|utensil|kitchen|crockery|cooker|stove|\bgas\b|pressure cooker|mess|bucket|mug|jug|tumbler|glass|flask|dispenser|oven|toaster|grinder, mixer|mixer|refrigerator|soap|detergent|disinfectant|phenyl|broom|mop|dustbin|toilet soap|sanitizer|tissue|napkin|household|water purifier|\bro\b"),
 ("Sports, Gym & Training","Goods",r"gym|fitness|treadmill|abductor|adductor|back extension|dumbbell|barbell|sport|game|football|cricket|volleyball|basketball|badminton|yoga|exercise|weight|cycle|bicycle|swimming|trophy|medal|simulator|training aid|selectorized"),
 ("Chemicals, Lubricants & Consumables","Goods",r"adhesive|silastic|altupol|compound|lubric|solvent|thinner|chemical|resin|epoxy|sealant|degreaser|cleaning agent|polish|acid|paint|varnish|primer|coolant|grease|oil\b|sealing"),
 ("Stationery, Printing & Office","Goods",r"stationery|paper|ribbon|pen\b|files?\b|folder|register|notebook|book|envelope|printing|carton|foam packing|packing|packaging|marker|stapler|calendar|diary|ink|label|sticker|photo|frame|certificate|office"),
]
def classify(item):
    s=item.lower()
    for cat,typ,rx in RULES:
        if re.search(rx,s): return cat,typ
    return "Other / Unclassified","Goods"
